version: '3'
services:
  redis:
    image: "redis:latest"
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    volumes:
      - ./:/asyncloader
  celery:
    build: .
    command: bash -c "apt-get update && apt-get install -y ffmpeg && celery -A videoloader worker -l info"
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379"
    volumes:
      - ./:/asyncloader


